development requirement installation: add whitelist mechanism
alphagov/docker-ckan pull request #33
Opened 2020-05-20 10:33 UTC by risicle

Extensions' dev requirements frequently conflict with each other. Attempting to install them all one after the other in the same env is a recipe for strangeness. Add `$DEV_EXTENSIONS_WHITELIST`, a comma-separated list of repo names to install dev dependencies for at startup. Ignored if not set.

2020-06-03 13:22 UTC, kentsanggds reviewed
Is this still needed? Do we need any documentation to explain the changes?

2020-06-03 13:51 UTC, risicle commented
For me it's needed - I can't get the `ckanext-datagovuk` 2.8 tests to pass if I let it just try installing all dev dependencies together. I need to specifically tell it to only install `ckanext-datagovuk`'s if that's what I'm going to run the tests for.

2020-06-03 14:22 UTC, kentsanggds requested changes
Can you add something in the README to explain what the variable is for and how to use it.

2020-06-03 16:18 UTC, kentsanggds commented
Can you also list the whitelist needed to get things passing in the README, probably in the Test section under ckanext-datagovuk.

2020-06-04 08:59 UTC, risicle commented
TBH I haven't found it very consistent. I've just got into the habit of setting it to the extension I'm about to run the tests for.

2020-06-15 15:45 UTC, kentsanggds approved these changes
Lets add this in as a way to help pass tests

2020-06-16 13:39 UTC, merged