Add branch to ckanext-datagovuk for 2.8
alphagov/docker-ckan pull request #35
Opened 2020-05-26 13:08 UTC by owenatgov

### What

Adds a branch param to the 2.8 bootstrap of ckanext-datagovuk. The variable `DATAGOVUK_BRANCH` is set at the top of the bootstrap script, set explicitly in the 2.8 if block and applied to the `git clone` via the `--branch` param.

### Why

We're currently using a branch off of master for ckanext-datagovuk called `master-2.8` for all ckan 2.8 work to prevent non-production ready code going into master (production is currently on ckan 2.7 which could be disrupted by the styling changes we're making). This ensures that docker-ckan references that branch when setting up the ckan project via docker-ckan.

2020-05-26 13:30 UTC, kentsanggds requested changes
I think this line will also need to be updated - https://github.com/alphagov/docker-ckan/blob/master/ckan-main/2.8/Dockerfile.dev#L27, to work with the branch in 2.8 and for 2.8 it may be worth adding additional output in `bootstrap.sh` to let the dev know that they need to remove the source folder for 2.8/ckanext-datagovuk to pull down the branch.

2020-05-26 13:36 UTC, risicle commented
TBH I've only ever run the bootstrap script once. I've then just switched around the existing repos to point at the appropriate branches when needed.

2020-05-26 14:31 UTC, owenatgov commented
> I think this line will also need to be updated - https://github.com/alphagov/docker-ckan/blob/master/ckan-main/2.8/Dockerfile.dev#L27, to work with the branch in 2.8 and for 2.8 it may be worth adding additional output in `bootstrap.sh` to let the dev know that they need to remove the source folder for 2.8/ckanext-datagovuk to pull down the branch.

Would this just be a case of replacing the line with `pip install -e git://github.com/alphagov/ckanext-datagovuk.git@master-2.8#egg=ckanext-datagovuk`?

I'm happy to throw in a little message. I feel like this should possibly be for all versions?

2020-05-27 11:03 UTC, kentsanggds commented
Looks like that might work, worth trying out on the docker container to see what happens.

I guess ideally what would be good if we can provide a warning to devs if the version in src does not match the intended version in the bootstrap. For now a general warning is probably ok for devs to checkout the right branch or remove the source directory and re-run bootstrap.

2020-05-28 15:14 UTC, owenatgov commented
@kentsanggds Changes done

2020-06-01 12:05 UTC, kentsanggds approved these changes
LGTM

2020-06-01 13:31 UTC, merged